services:
  donation-service:
    container_name: donation-service
    image: donation-service:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3001:3001
      - 9229:9229
    env_file:
      - .env
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    restart: unless-stopped
  mongo_donation_service:
    container_name: mongo_donation_service
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_donation_service_data:/data/db

volumes:
  mongo_donation_service_data:

configs:
  httpd-config:
    external: true
