import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { INestApplication } from '@nestjs/common';

export function setupSwagger(app: INestApplication) {
  const config = new DocumentBuilder()
    .setTitle('Sangue Solidário - Donation Service API')
    .setDescription(`
      ## Donation Service API Documentation
      
      This microservice handles blood donation requests and donor registrations for the Sangue Solidário platform.
      
      ### Features
      - Blood donation request management
      - Donor registration for donations
      - Geographic location handling
      - Status tracking and updates
      - Pagination support
      
      ### Authentication
      Most endpoints require JWT authentication. The service validates JWT tokens generated by the Users Service.
      
      ### Protected Endpoints
      - \`POST /donations\` - Create donation
      - \`PUT /donations/:id/status\` - Update donation status
      - \`DELETE /donations/:id\` - Delete donation
      
      ### Base URL
      \`http://localhost:8080\`
      
      ### JWT Token
      Include the JWT token in the Authorization header:
      \`\`\`
      Authorization: Bearer <your-jwt-token>
      \`\`\`
    `)
    .setVersion('1.0.0')
    .addTag('Donations', 'Blood donation requests management')
    .addTag('Registrations', 'Donor registrations for donations')
    .addBearerAuth(
      {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
        name: 'JWT',
        description: 'Enter JWT token from Users Service',
        in: 'header',
      },
      'JWT-auth',
    )
    .addServer('http://localhost:8080', 'Development Server')
    .addServer('https://donation-api.sanguesolidario.com', 'Production Server')
    .build();

  const document = SwaggerModule.createDocument(app, config, {
    operationIdFactory: (controllerKey: string, methodKey: string) => methodKey,
  });

  SwaggerModule.setup('api-docs', app, document, {
    swaggerOptions: {
      persistAuthorization: true,
      displayRequestDuration: true,
      docExpansion: 'none',
      filter: true,
      showRequestHeaders: true,
      showCommonExtensions: true,
      tryItOutEnabled: true,
    },
    customSiteTitle: 'Sangue Solidário - Donation Service API',
    customfavIcon: '/favicon.ico',
    customCss: `
      .swagger-ui .topbar { display: none; }
      .swagger-ui .info .title { color: #e74c3c; }
      .swagger-ui .scheme-container { background: #f8f9fa; padding: 10px; border-radius: 4px; }
    `,
  });

  return document;
}
